name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: echo de variables de entorno
        run: |
          echo "DBHost=${{ secrets.DBHOST }}" 
          echo "DBUser=${{ secrets.DBUSER }}"
          echo "DBPassword=${{ secrets.DBPASSWORD }}"
          echo "DBName=${{ secrets.DBNAME }}" >> 
          echo "DBPort=${{ secrets.DBPORT }}" >>

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go app
        run: go run main.go
