name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: echo de variables de entorno
        run: |
          echo "DBHost=${{ secrets.DBHOST }}" 
          echo "DBUser=${{ secrets.DBUSER }}"
          echo "DBPassword=${{ secrets.DBPASSWORD }}"
          echo "DBName=${{ secrets.DBNAME }}" >> 
          echo "DBPort=${{ secrets.DBPORT }}" >>

      - name: Install dependencies
        run: go mod tidy

      - name: Crea un archivo .env con las variables de entorno
        run: |
          echo "DBHost=${{ secrets.DBHOST }}" >> .env
          echo "DBUser=${{ secrets.DBUSER }}" >> .env
          echo "DBPassword=${{ secrets.DBPASSWORD }}" >> .env
          echo "DBName=${{ secrets.DBNAME }}" >> .env
          echo "DBPort=${{ secrets.DBPORT }}" >> .env

      - name: Verifica que el archivo .env se haya creado
        run: cat .env

      - name: Run Go app
        run: go run main.go
